# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
    tags: [ bobross-v** ]
  pull_request:
    branches: [ master ]
    tags: [ bobross-v** ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: hpi
        path: target/bobross.hpi
  
  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: hpi
        path: target/bobross.hpi
    - name: Release
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_COMPRESS: gz
        GHR_PATH: target/bobross.hpi
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
